//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacto
    {
        public int id_contacto { get; set; }
        public string nombres { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
    }
}
