//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int id_evento { get; set; }
        public string nombre_evento { get; set; }
        public System.DateTime fecha { get; set; }
        public string lugar { get; set; }
        public string fe { get; set; }
    }
}
